### ISSUE TITLE
Fail to instantiate on Ubuntu

### ISSUE THREAD

**Issue by Paalon** [BioJulia/BioSequences.jl#100]
## Current Behavior

In Ubuntu, fail to instantiate a package which contains BioSequences if the package is created in macOS.

## Steps to Reproduce

Generate the follwing `BSTest` package in Julia REPL on macOS.

```julia
paalon at mac in ~/git
↪ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> generate BSTest
 Generating  project BSTest:
    BSTest/Project.toml
    BSTest/src/BSTest.jl

(@v1.4) pkg> activate BSTest
 Activating environment at `~/git/BSTest/Project.toml`

(BSTest) pkg> registry add https://github.com/BioJulia/BioJuliaRegistry.git
    Cloning registry from "https://github.com/BioJulia/BioJuliaRegistry.git"
registry `BioJuliaRegistry` already exist in `~/.julia/registries/BioJuliaRegistry`.

(BSTest) pkg> add BioSequences
   Updating registry at `~/.julia/registries/BioJuliaRegistry`
   Updating git-repo `https://github.com/BioJulia/BioJuliaRegistry.git`
   Updating registry at `~/.julia/registries/General`
   Updating git-repo `https://github.com/JuliaRegistries/General.git`
  Resolving package versions...
   Updating `~/git/BSTest/Project.toml`
  [7e6ae17a] + BioSequences v2.0.1
   Updating `~/git/BSTest/Manifest.toml`
  [67c07d97] + Automa v0.8.0
  [47718e42] + BioGenerics v0.1.0
  [7e6ae17a] + BioSequences v2.0.1
  [3c28c6f8] + BioSymbols v4.0.3
  [861a8166] + Combinatorics v1.0.0
  [864edb3b] + DataStructures v0.17.11
  [1cb3b9ac] + IndexableBitVectors v1.0.0
  [bac558e1] + OrderedCollections v1.1.0
  [f27b6e38] + Polynomials v0.5.3
  [3cdcf5f2] + RecipesBase v1.0.0
  [3bb67fe8] + TranscodingStreams v0.9.5
  [7200193e] + Twiddle v1.1.1
  [2a0f44e3] + Base64
  [8ba89e20] + Distributed
  [b77e0a4c] + InteractiveUtils
  [8f399da3] + Libdl
  [37e2e46d] + LinearAlgebra
  [56ddb016] + Logging
  [d6f4376e] + Markdown
  [de0858da] + Printf
  [9a3f8284] + Random
  [9e88b42a] + Serialization
  [6462fe0b] + Sockets
  [8dfed614] + Test
  [4ec0a83e] + Unicode

(BSTest) pkg> st
Project BSTest v0.1.0
Status `~/git/BSTest/Project.toml`
  [7e6ae17a] BioSequences v2.0.1

(BSTest) pkg> instantiate

julia> using BSTest
[ Info: Precompiling BSTest [f5260244-0a45-42a5-ad8a-78ba73d8e808]

julia> exit()
paalon at mac in ~/git
↪ ls
BSTest/
paalon at mac in ~/git
↪ 
```

Copy this package to Ubuntu, then instantiate.

```julia
paalon at ubuntu-bionic in ~/git
↪ ls
BSTest/
paalon at ubuntu-bionic in ~/git
↪ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> activate BSTest
 Activating environment at `~/git/BSTest/Project.toml`

(BSTest) pkg> registry add https://github.com/BioJulia/BioJuliaRegistry.git
    Cloning registry from "https://github.com/BioJulia/BioJuliaRegistry.git"
      Added registry `BioJuliaRegistry` to `~/.julia/registries/BioJuliaRegistry`

(BSTest) pkg> st
Project BSTest v0.1.0
Status `~/git/BSTest/Project.toml`
→ [7e6ae17a] BioSequences v2.0.1
┌ Warning: Some packages (indicated with a red arrow) are not downloaded, use `instantiate` to instantiate the current environment
└ @ Pkg.Display /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.4/Pkg/src/Display.jl:238

(BSTest) pkg> instantiate
   Updating registry at `~/.julia/registries/BioJuliaRegistry`
   Updating git-repo `https://github.com/BioJulia/BioJuliaRegistry.git`
ERROR: expected package `Combinatorics [861a8166]` to be registered

(BSTest) pkg>
```
## My Environment

macOS 10.15.4 Catalina 

```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.6.0)
  CPU: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

Ubuntu 18.04.4 LTS (Bionic Beaver)

```
Julia Version 1.4.0
Commit b8e9a9ecc6 (2020-03-21 16:36 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-8.0.1 (ORCJIT, skylake)
```

**Comment by kescobo** [comment]
After you activate the package, can you do `] instantiate` and `] resolve`?

If those don't work, can you copy the contents of the `Manifest.toml` file? [Combinatorics](https://github.com/JuliaMath/Combinatorics.jl) is definitely registered (in General), I wonder if you have a weird path somewhere. Did you ever `dev` that package?

**Comment by Paalon** [comment]
```julia
paalon at ubuntu-bionic in ~/git
↪ rm -rf ~/.julia
paalon at ubuntu-bionic in ~/git
↪ ls
BSTest/
paalon at ubuntu-bionic in ~/git
↪ julia
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> registry add https://github.com/BioJulia/BioJuliaRegistry.git
    Cloning registry from "https://github.com/BioJulia/BioJuliaRegistry.git"
      Added registry `BioJuliaRegistry` to `~/.julia/registries/BioJuliaRegistry`

(@v1.4) pkg> activate BSTest
 Activating environment at `~/git/BSTest/Project.toml`

(BSTest) pkg> instantiate
   Updating registry at `~/.julia/registries/BioJuliaRegistry`
   Updating git-repo `https://github.com/BioJulia/BioJuliaRegistry.git`
ERROR: expected package `Combinatorics [861a8166]` to be registered

(BSTest) pkg> resolve
ERROR: expected package `Combinatorics [861a8166]` to be registered

```

Manifest.toml is

```toml
# This file is machine-generated - editing it directly is not advised

[[Automa]]
deps = ["DataStructures", "Printf", "Random", "Test", "TranscodingStreams"]
git-tree-sha1 = "c81526bf5f6fb4616b4e22a3cd62ac20e255fd3c"
uuid = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"
version = "0.8.0"

[[Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[BioGenerics]]
deps = ["TranscodingStreams"]
git-tree-sha1 = "57deb413ca9f4c8bc7d4c6e98ebe217ff728c737"
uuid = "47718e42-2ac5-11e9-14af-e5595289c2ea"
version = "0.1.0"

[[BioSequences]]
deps = ["BioGenerics", "BioSymbols", "Combinatorics", "IndexableBitVectors", "Printf", "Random", "Twiddle"]
git-tree-sha1 = "92da3f46866826c386ada963bfd616899aa24543"
uuid = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
version = "2.0.1"

[[BioSymbols]]
deps = ["Automa"]
git-tree-sha1 = "1b1753fa7e74209a8d58082e6e993ae170f38676"
uuid = "3c28c6f8-a34d-59c4-9654-267d177fcfa9"
version = "4.0.3"

[[Combinatorics]]
deps = ["Polynomials"]
git-tree-sha1 = "140cc833258df8e5aafabdb068875ac0c256be23"
uuid = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
version = "1.0.0"

[[DataStructures]]
deps = ["InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "73eb18320fe3ba58790c8b8f6f89420f0a622773"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.17.11"

[[Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[IndexableBitVectors]]
deps = ["Random", "Test"]
git-tree-sha1 = "b7f5e42dc867b8a8654a5f899064632dac05bc82"
uuid = "1cb3b9ac-1ffd-5777-9e6b-a3d42300664d"
version = "1.0.0"

[[InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[OrderedCollections]]
deps = ["Random", "Serialization", "Test"]
git-tree-sha1 = "c4c13474d23c60d20a67b217f1d7f22a40edf8f1"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.1.0"

[[Polynomials]]
deps = ["LinearAlgebra", "RecipesBase"]
git-tree-sha1 = "f7c0c07e82798aef542d60a6e6e85e39f4590750"
uuid = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
version = "0.5.3"

[[Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[Random]]
deps = ["Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[RecipesBase]]
git-tree-sha1 = "d352369b00094cadb43d694333b051b3d55abaf2"
uuid = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
version = "1.0.0"

[[Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[Test]]
deps = ["Distributed", "InteractiveUtils", "Logging", "Random"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "7c53c35547de1c5b9d46a4797cf6d8253807108c"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.5"

[[Twiddle]]
git-tree-sha1 = "475f0c0e1633b51e81cf92099356fcb4029a9e19"
uuid = "7200193e-83a8-5a55-b20d-5d36d44a0795"
version = "1.1.1"

[[Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"
```

**Comment by Paalon** [comment]
I noticed that if I instantiate before adding the registry, it correctly recognize General and correctly fail that it has not BioGenerics. Then, adding the BioJuliaRegistry, it works.

```sh
vagrant at ubuntu-bionic in ~/git
↪ rm -rf ~/.julia                                                                                                 (base)
vagrant at ubuntu-bionic in ~/git
↪ julia                                                                                                           (base)
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.4.0 (2020-03-21)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

(@v1.4) pkg> activate BSTest
 Activating environment at `~/git/BSTest/Project.toml`

(BSTest) pkg> instantiate
    Cloning default registries into `~/.julia`
    Cloning registry from "https://github.com/JuliaRegistries/General.git"
      Added registry `General` to `~/.julia/registries/General`
ERROR: expected package `BioGenerics [47718e42]` to be registered

(BSTest) pkg> registry add https://github.com/BioJulia/BioJuliaRegistry.git
    Cloning registry from "https://github.com/BioJulia/BioJuliaRegistry.git"
      Added registry `BioJuliaRegistry` to `~/.julia/registries/BioJuliaRegistry`

(BSTest) pkg> instantiate
  Installed Combinatorics ─────── v1.0.0
  Installed Polynomials ───────── v0.5.3
  Installed Twiddle ───────────── v1.1.1
  Installed Automa ────────────── v0.8.0
  Installed DataStructures ────── v0.17.11
  Installed BioSymbols ────────── v4.0.3
  Installed IndexableBitVectors ─ v1.0.0
  Installed RecipesBase ───────── v1.0.0
  Installed BioGenerics ───────── v0.1.0
  Installed OrderedCollections ── v1.1.0
  Installed TranscodingStreams ── v0.9.5
  Installed BioSequences ──────── v2.0.1

```

**Comment by Paalon** [comment]
It's a bug of Pkg?

**Comment by kescobo** [comment]
Huh, interesting. Might be a Pkg bug - are you able to share the offending package with me? Even just the Project.toml plus Manifest.toml you've already shared should be sufficient. I'll see if I can reproduce and build a MWE, then open an issue.

Glad you found a workaround, but let's leave this issue open for now.

**Comment by Paalon** [comment]
Project.toml

```toml
name = "BSTest"
uuid = "f5260244-0a45-42a5-ad8a-78ba73d8e808"
authors = ["Koki Fushimi <paalon1936@gmail.com>"]
version = "0.1.0"

[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
```
